# Exploring Data

## Initialization

In [1]:
import pandas as pd
from IPython.core.display import HTML

df = pd.read_csv("./csv/pichu_lv9.csv", index_col=False)
df.head()

      opponent  win  lose
0        Mario    1     0
1  Donkey Kong    1     0
2         Link    1     0
3        Samus    3     0
4   Dark Samus    2     0

## Sorting by win rate

In [2]:
df["playcount"] = df["win"] + df["lose"]
df["win_rate"] = round(df["win"] / (df["win"] + df["lose"])*1000)/10

display(HTML(df.sort_values(by=["win_rate", "opponent"], ascending=False).dropna().to_html()))

## Most encountered

In [3]:
display(HTML(df.sort_values(by=["playcount", "opponent"], ascending=False).to_html()))
# display(df.sort_values(by="playcount", ascending=False))

## Global win rate & playcount

### Global win rate

In [4]:
print(df["win"].sum() / df["playcount"].sum() * 100, "%")

79.43925233644859 %

### Global playcount

In [5]:
print(df["playcount"].sum(), "games")

107 games